spring:
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/demo
        username: demo
        password: demo1234
    thymeleaf:
        check-template-location: true
        prefix: classpath:templates/
        suffix: .html
        mode: HTML5
        cache: false
    jpa:
        hibernate:
            ddl-auto: update
            use-new-id-generator-mappings: true